### ISSUE TITLE
Cromshell2.0 crashes for server that worked on cromshell 1

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/cromshell#269]
When I try to connect to a cromshell server with that I could contact with cromshell 1 by <IP:Port> I get the following exception:

```
2023-07-31 17:01:08,951 cromshell.utilities.http_utils                ERROR    Failed to connect to <IP:Port>
Traceback (most recent call last):
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/cromshell/utilities/http_utils.py", line 16, in assert_can_communicate_with_server
    request_out = requests.get(
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '34.73.109.5:8000/api/workflows/v1/backends'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cromshell", line 8, in <module>
    sys.exit(main_entry())
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/cromshell/submit/command.py", line 66, in main
    http_utils.assert_can_communicate_with_server(config=config)
  File "/usr/local/Cellar/cromshell/2.0.0/libexec/lib/python3.9/site-packages/cromshell/utilities/http_utils.py", line 27, in assert_can_communicate_with_server
    raise Exception(f"Failed to connect to {config.cromwell_server}")
Exception: Failed to connect to <IP:Port>
```
 
I would be happy to DM about the server in question. I have tested and confirm that the very same IP and port work fine for submissions on Cromwell1. I've heard speculation that it could be the format or the version of cromwell running on the server that is causing problems.

**Comment by SHuang-Broad** [comment]
Just FYI, the server IP is in the stack trace (just in case you don't want that exposed).
